# Generated by Django 3.0.8 on 2022-02-28 08:48

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActFinancieras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=75, unique=True)),
                ('clave', fernet_fields.fields.EncryptedTextField()),
                ('habilitado', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='Perfiles')),
                ('conf_correo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('inversion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tasa_retorno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('periodo_anio', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='Simulador.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='FlujoEfectivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Simulador.ActFinancieras')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_efectivos', to='Simulador.Proyectos')),
            ],
        ),
        migrations.AddField(
            model_name='actfinancieras',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Simulador.Proyectos'),
        ),
        migrations.AddField(
            model_name='actfinancieras',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Simulador.TiposCuentas'),
        ),
    ]
