# Generated by Django 3.0.8 on 2022-02-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tiposcuentas',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
