# Generated by Django 3.0.8 on 2022-02-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador', '0002_auto_20220201_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
