# Generated by Django 3.0.8 on 2022-02-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador', '0002_auto_20220201_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flujoefectivos',
            old_name='inversion',
            new_name='valor',
        ),
    ]
