# Generated by Django 3.0.8 on 2022-02-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador', '0003_auto_20220222_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujoefectivos',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_efectivos', to='Simulador.Proyectos'),
        ),
    ]
