# Generated by Django 3.0.8 on 2022-02-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador', '0004_auto_20220223_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujoefectivos',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Simulador.ActFinancieras'),
        ),
    ]
