# Generated by Django 3.0.8 on 2022-02-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador', '0003_auto_20220223_0148'),
        ('Simulador', '0005_auto_20220223_0041'),
    ]

    operations = [
    ]
